name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: 'voidlinux/voidlinux:latest'

    steps:
      - name: Prepare container
        run: |
          # Update system
          xbps-install -Syu || xbps-install -yu xbps
          # Update system for sure (in case XBPS has been updated)
          xbps-install -yu
          # Install dependencies
          xbps-install -y git make gcc go pkg-config gtk+-devel

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build without tags
        run: |
          # Make clean
          make clean
          # Make build
          make build

      - name: Test install
        run: |
          # Make install
          make install
          # Make uninstall
          make uninstall
